### PR TITLE
Add TURN support

### PR DESCRIPTION
**Pull request by farao**
The TURN server url can be set via environment variable VUE_APP_TURN_URL.

### CODE REVIEW

**Comment by farao** [comment]
Needs testing together with https://github.com/palavatv/signaltower/pull/30 and https://github.com/palavatv/palava-client/pull/30.

**Comment by janlelis** [comment]
Awesome to see this finally being tackled!

**Comment by janlelis** [comment]
@farao Looks good, and I just wanted to merge, however one thing just came to my mind: How should we configure multiple TURN servers?

**Comment by farao** [comment]
Let's tackle multiple TURN servers in a future PR to not let this get too large, ok?

**Comment by janlelis** [comment]
https://github.com/palavatv/palava/issues/45

**Pull request merged**
